name: trunriproject
description: "TruNri"
publish_to: 'none' 

version: 1.0.1+2

environment:
  sdk: '>=3.4.0-190.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  razorpay_flutter: ^1.4.0
  permission_handler: ^12.0.1
  map_location_picker: ^3.1.0
  get: ^4.7.2
  flutter_pin_code_fields: ^2.2.0
  smooth_page_indicator: ^1.2.1
  provider: ^6.1.5
  animate_do: ^4.2.0
  firebase_messaging: ^16.0.4
  pin_code_fields: ^8.0.1
  printing: 
  pdf: ^3.11.3
  google_fonts: ^6.2.1
  pinput: ^6.0.0
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  connectivity_plus: ^7.0.0
  form_field_validator: ^1.1.0
  loading_animation_widget: ^1.2.0+4
  flutter_animate: ^4.2.0+1
  google_sign_in: ^7.2.0
  image_picker: ^1.1.2
  emoji_picker_flutter: ^4.3.0
  path: ^1.9.1
  email_otp: ^3.0.2
  sign_in_with_apple: ^7.0.1
  shared_preferences: ^2.2.3
  qr_flutter: ^4.1.0
  lottie: ^3.1.0
  flutter_google_places_hoc081098:
  geocoding:
  google_api_headers:
  google_maps_flutter: ^2.6.1
  geolocator:
  email_auth: ^2.0.0
  intl_phone_field: ^3.2.0
  dots_indicator: ^4.0.1
  carousel_slider: ^5.0.0
  animated_bottom_navigation_bar: ^1.3.3
  cached_network_image: ^3.3.1
  get_it: ^8.3.0
  video_player: ^2.8.6
  stacked_services: ^1.5.0
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.2.6
  url_launcher_ios: ^6.3.3
  http: ^1.2.1
  firebase_storage: ^13.0.4
  share_plus: ^12.0.1
  dio: ^5.4.3+1
  path_provider: ^2.1.3
  file_picker: ^10.3.7
  uuid: ^4.4.0
  intl: ^0.20.2
  dotted_border: ^3.1.0
  smart_auth: ^3.2.0
  font_awesome_flutter: ^10.9.1
  icons_plus: ^5.0.0

dependency_overrides:
  retrofit: 4.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png" # Path to your 1024x1024 icon

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/loti/
    - assets/icons/

  fonts:
     - family: Caveat
       fonts:
         - asset: assets/fonts/Caveat-VariableFont_wght.ttf
